In [87]:
import pandas as pd
import os
from datetime import datetime
from dateutil.relativedelta import relativedelta

In [88]:
s2 = pd.Series([1,2,3,4,5], index=['a','b','c','d','e'])

print(s2)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [89]:
s3 = pd.Series(
    {
        'a':10,
        'b':20,
        'c':30
    },
    index=['b','c','a','d']
)
print(s3)

b    20.0
c    30.0
a    10.0
d     NaN
dtype: float64

In [90]:
s5 = pd.Series([1,2,3,4,5,6])
s6 = pd.Series([4,5,7,8,9,10])
df = pd.concat([s5,s6], axis = 1)
df

   0   1
0  1   4
1  2   5
2  3   7
3  4   8
4  5   9
5  6  10

In [91]:
s5[0:6:2]

0    1
2    3
4    5
dtype: int64

In [92]:
df = pd.DataFrame(
    {
        'Name':['Sudip', 'Ram', 'saffi','bibek', 'grishma'],
        'age':[22,34,11,33,23],
        'address':['ktm','chitwan','butwal','ktm','bkt'],
        'marks':[90,34,98,56,77]
    }
)
df

      Name  age  address  marks
0    Sudip   22      ktm     90
1      Ram   34  chitwan     34
2    saffi   11   butwal     98
3    bibek   33      ktm     56
4  grishma   23      bkt     77

In [93]:
df[['Name','address']].head()

      Name  address
0    Sudip      ktm
1      Ram  chitwan
2    saffi   butwal
3    bibek      ktm
4  grishma      bkt

In [94]:
df[['Name','address']][(df['address']=='ktm') | (df['Name'] == 'Sudip')]

    Name address
0  Sudip     ktm
3  bibek     ktm

In [95]:
ep = pd.DataFrame(
{
'Name':['Ram','Syam','Hari','Rakesh','Sita','Uma','Rajesh','Susma','Susmita','Rita',
        'Alisha','Alix','Sudipa','Ema','Monika','Nisha','Abin','Ankit','Tulsi','Pujan',
        'Puja','Priti','Manish','Laxmi','Bibek','Milen'],

'Gender':['Male','Male','Male','Male','Female','Female','Male','Female','Female','Female',
          'Female','Male','Female','Female','Female','Female','Male','Male','Female','Male',
          'Female','Female','Male','Female','Male','Male'],

'DateOfBirth':['2004-02-25','2003-04-10','1995-06-12','1981-08-15','1991-01-14',
               '2002-03-19','2001-07-21','2004-11-30','2006-09-12','2000-12-05',
               '1969-04-18','1938-06-22','1980-08-17','2002-10-09','2013-12-31',
               '2013-02-11','2011-03-27','2003-05-16','2000-07-29','1999-09-03',
               '1997-11-24','1996-01-08','2008-04-14','2007-06-20','2006-08-25',
               '2005-10-13'],

'Age':[21,22,30,44,34,23,24,21,19,25,
       56,87,45,23,12,12,14,22,25,26,
       28,29,17,18,19,20],

'DateOfDeath':['ALIVE','2025-02-28','ALIVE','ALIVE','ALIVE',
               'ALIVE','ALIVE','ALIVE','ALIVE','ALIVE',
               'ALIVE','2010-08-10','ALIVE','ALIVE','ALIVE',
               'ALIVE','ALIVE','ALIVE','ALIVE','ALIVE',
               'ALIVE','ALIVE','ALIVE','ALIVE','ALIVE','2025-08-11'],

'Address':['Chitwan','Ktm','Bhaktapur','Chitwan','Butwal','Pokhara','Damauli','Ktm','Lalitpur','Dharan',
           'Biratnagar','Janakpur','Hetauda','Ilam','Nepalgunj','Dang','Gorkha','Bardiya','Bhairahawa','Kailali',
           'Kanchanpur','Surkhet','Palpa','Rolpa','Jhapa','Lamjung'],

'Salary':[20000,45000,30000,34500,50000,28000,32000,40000,22000,26000,
          70000,90000,60000,35000,15000,16000,18000,42000,38000,39000,
          41000,43000,21000,23000,24000,25000],

'Post':['HR','Designer','Receptionist','Junior Developer','Java Developer','Manager',
        'Accountant','QA Engineer','Intern','Support Staff',
        'Senior Manager','Director','Team Lead','Developer','Trainee',
        'Trainee','Assistant','Engineer','Supervisor','Officer',
        'Officer','Analyst','Intern','Clerk','Technician','Developer'],

'Education':['BBA','BCA','+2','BIT','Software Engineer','MBA',
             'BBS','BSc CSIT','+2','BBA',
             'MBA','PhD','MIT','BCA','SEE',
             'SEE','+2','BE','BBA','MBS',
             'MBS','MBA','+2','+2','Diploma','BIT'],

'CGPA':[3.30,2.80,3.45,4.00,3.75,3.60,
        3.10,3.85,2.90,3.20,
        3.95,4.00,3.70,3.50,2.50,
        2.60,2.80,3.40,3.30,3.60,
        3.55,3.75,2.70,2.85,3.00,3.65]
}
)

ep

,Name,Gender,DateOfBirth,Age,DateOfDeath,Address,Salary,Post,Education,CGPA
0,Ram,Male,2004-02-25,21,ALIVE,Chitwan,20000,HR,BBA,3.30
1,Syam,Male,2003-04-10,22,2025-02-28,Ktm,45000,Designer,BCA,2.80
2,Hari,Male,1995-06-12,30,ALIVE,Bhaktapur,30000,Receptionist,+2,3.45
3,Rakesh,Male,1981-08-15,44,ALIVE,Chitwan,34500,Junior Developer,BIT,4.00
4,Sita,Female,1991-01-14,34,ALIVE,Butwal,50000,Java Developer,Software Engineer,3.75
5,Uma,Female,2002-03-19,23,ALIVE,Pokhara,28000,Manager,MBA,3.60
6,Rajesh,Male,2001-07-21,24,ALIVE,Damauli,32000,Accountant,BBS,3.10
7,Susma,Female,2004-11-30,21,ALIVE,Ktm,40000,QA Engineer,BSc CSIT,3.85
8,Susmita,Female,2006-09-12,19,ALIVE,Lalitpur,22000,Intern,+2,2.90
9,Rita,Female,2000-12-05,25,ALIVE,Dharan,26000,Support Staff,BBA,3.20
10,Alisha,Female,1969-04-18,56,ALIVE,Biratnagar,70000,Senior Manager,MBA,3.95
11,Alix,Male,1938-06-22,87,2010-08-10,Janakpur,90000,Director,PhD,4.00
12,Sudipa,Female,1980-08-17,45,ALIVE,Hetauda,60000,Team Lead,MIT,3.70
13,Ema,Female,2002-10-09,23,ALIVE,Ilam,35000,Developer,BCA,3.50
14,Monika,Female,2013-12-31,12,ALIVE,Nepalgunj,15000,Trainee,SEE,2.50
15,Nisha,Female,2013-02-11,12,ALIVE,Dang,16000,Trainee,SEE,2.60
16,Abin,Male,2011-03-27,14,ALIVE,Gorkha,18000,Assistant,+2,2.80
17,Ankit,Male,2003-05-16,22,ALIVE,Bardiya,42000,Engineer,BE,3.40
18,Tulsi,Female,2000-07-29,25,ALIVE,Bhairahawa,38000,Supervisor,BBA,3.30
19,Pujan,Male,1999-09-03,26,ALIVE,Kailali,39000,Officer,MBS,3.60
20,Puja,Female,1997-11-24,28,ALIVE,Kanchanpur,41000,Officer,MBS,3.55
21,Priti,Female,1996-01-08,29,ALIVE,Surkhet,43000,Analyst,MBA,3.75
22,Manish,Male,2008-04-14,17,ALIVE,Palpa,21000,Intern,+2,2.70
23,Laxmi,Female,2007-06-20,18,ALIVE,Rolpa,23000,Clerk,+2,2.85
24,Bibek,Male,2006-08-25,19,ALIVE,Jhapa,24000,Technician,Diploma,3.00
25,Milen,Male,2005-10-13,20,2025-08-11,Lamjung,25000,Developer,BIT,3.65

In [96]:
ep.dtypes

Name            object
Gender          object
DateOfBirth     object
Age              int64
DateOfDeath     object
Address         object
Salary           int64
Post            object
Education       object
CGPA           float64
dtype: object

In [97]:
ep['Salary'] = ep['Salary'].astype(float)

In [98]:
ep.dtypes

Name            object
Gender          object
DateOfBirth     object
Age              int64
DateOfDeath     object
Address         object
Salary         float64
Post            object
Education       object
CGPA           float64
dtype: object

In [99]:
ep[ep['Salary'] >= 50000]

,Name,Gender,DateOfBirth,Age,DateOfDeath,Address,Salary,Post,Education,CGPA
4,Sita,Female,1991-01-14,34,ALIVE,Butwal,50000.0,Java Developer,Software Engineer,3.75
10,Alisha,Female,1969-04-18,56,ALIVE,Biratnagar,70000.0,Senior Manager,MBA,3.95
11,Alix,Male,1938-06-22,87,2010-08-10,Janakpur,90000.0,Director,PhD,4.00
12,Sudipa,Female,1980-08-17,45,ALIVE,Hetauda,60000.0,Team Lead,MIT,3.70

In [100]:
ep['DateOfBirth'] = pd.to_datetime(ep['DateOfBirth'])

In [101]:
ep.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Name         26 non-null     object
 1   Gender       26 non-null     object
 2   DateOfBirth  26 non-null     datetime64[ns]
 3   Age          26 non-null     int64
 4   DateOfDeath  26 non-null     object
 5   Address      26 non-null     object
 6   Salary       26 non-null     float64
 7   Post         26 non-null     object
 8   Education    26 non-null     object
 9   CGPA         26 non-null     float64
dtypes: datetime64[ns](1), float64(2), int64(1), object(6)
memory usage: 2.2+ KB

In [102]:
ep.drop('Age', inplace = True, axis = 1)

In [103]:
ep.head()

,Name,Gender,DateOfBirth,DateOfDeath,Address,Salary,Post,Education,CGPA
0,Ram,Male,2004-02-25,ALIVE,Chitwan,20000.0,HR,BBA,3.30
1,Syam,Male,2003-04-10,2025-02-28,Ktm,45000.0,Designer,BCA,2.80
2,Hari,Male,1995-06-12,ALIVE,Bhaktapur,30000.0,Receptionist,+2,3.45
3,Rakesh,Male,1981-08-15,ALIVE,Chitwan,34500.0,Junior Developer,BIT,4.00
4,Sita,Female,1991-01-14,ALIVE,Butwal,50000.0,Java Developer,Software Engineer,3.75

In [104]:
today = datetime.today()
today

datetime.datetime(2026, 3, 5, 10, 24, 13, 981090)

In [105]:
def calculate_age(dob):
    diff = relativedelta(today,dob)
    return f'{diff.years} year {diff.months} months {diff.days} days'

In [106]:
ep['age'] = ep['DateOfBirth'].apply(calculate_age)

In [107]:
ep.head()

,Name,Gender,DateOfBirth,DateOfDeath,Address,Salary,Post,Education,CGPA,age
0,Ram,Male,2004-02-25,ALIVE,Chitwan,20000.0,HR,BBA,3.30,22 year 0 months 8 days
1,Syam,Male,2003-04-10,2025-02-28,Ktm,45000.0,Designer,BCA,2.80,22 year 10 months 23 days
2,Hari,Male,1995-06-12,ALIVE,Bhaktapur,30000.0,Receptionist,+2,3.45,30 year 8 months 21 days
3,Rakesh,Male,1981-08-15,ALIVE,Chitwan,34500.0,Junior Developer,BIT,4.00,44 year 6 months 18 days
4,Sita,Female,1991-01-14,ALIVE,Butwal,50000.0,Java Developer,Software Engineer,3.75,35 year 1 months 19 days

In [108]:
ep['Post'].value_counts

<bound method IndexOpsMixin.value_counts of 0                   HR
1             Designer
2         Receptionist
3     Junior Developer
4       Java Developer
5              Manager
6           Accountant
7          QA Engineer
8               Intern
9        Support Staff
10      Senior Manager
11            Director
12           Team Lead
13           Developer
14             Trainee
15             Trainee
16           Assistant
17            Engineer
18          Supervisor
19             Officer
20             Officer
21             Analyst
22              Intern
23               Clerk
24          Technician
25           Developer
Name: Post, dtype: object>

In [109]:
ep.groupby('Post')['Salary'].mean().sort_values(ascending=False)

Post
Director            90000.0
Senior Manager      70000.0
Team Lead           60000.0
Java Developer      50000.0
Designer            45000.0
Analyst             43000.0
Engineer            42000.0
QA Engineer         40000.0
Officer             40000.0
Supervisor          38000.0
Junior Developer    34500.0
Accountant          32000.0
Receptionist        30000.0
Developer           30000.0
Manager             28000.0
Support Staff       26000.0
Technician          24000.0
Clerk               23000.0
Intern              21500.0
HR                  20000.0
Assistant           18000.0
Trainee             15500.0
Name: Salary, dtype: float64

In [110]:
ep['New_Salary'] = ep['Salary']
ep.loc[(ep['CGPA'] > 3.5) & (ep['Gender'] == 'Male'), 'New_Salary'] = ep['Salary'] * 1.15

In [111]:
ep.head()

,Name,Gender,DateOfBirth,DateOfDeath,Address,Salary,Post,Education,CGPA,age,New_Salary
0,Ram,Male,2004-02-25,ALIVE,Chitwan,20000.0,HR,BBA,3.30,22 year 0 months 8 days,20000.0
1,Syam,Male,2003-04-10,2025-02-28,Ktm,45000.0,Designer,BCA,2.80,22 year 10 months 23 days,45000.0
2,Hari,Male,1995-06-12,ALIVE,Bhaktapur,30000.0,Receptionist,+2,3.45,30 year 8 months 21 days,30000.0
3,Rakesh,Male,1981-08-15,ALIVE,Chitwan,34500.0,Junior Developer,BIT,4.00,44 year 6 months 18 days,39675.0
4,Sita,Female,1991-01-14,ALIVE,Butwal,50000.0,Java Developer,Software Engineer,3.75,35 year 1 months 19 days,50000.0

In [112]:
ep['Updated_Salary'] = ep.apply(
    lambda x: x['Salary'] * 1.15 
    if (x['Gender'] == 'Female') & (x['CGPA'] > 3) 
    else x['Salary'],
    axis=1
)

In [113]:
ep

,Name,Gender,DateOfBirth,DateOfDeath,Address,Salary,Post,Education,CGPA,age,New_Salary,Updated_Salary
0,Ram,Male,2004-02-25,ALIVE,Chitwan,20000.0,HR,BBA,3.30,22 year 0 months 8 days,20000.0,20000.0
1,Syam,Male,2003-04-10,2025-02-28,Ktm,45000.0,Designer,BCA,2.80,22 year 10 months 23 days,45000.0,45000.0
2,Hari,Male,1995-06-12,ALIVE,Bhaktapur,30000.0,Receptionist,+2,3.45,30 year 8 months 21 days,30000.0,30000.0
3,Rakesh,Male,1981-08-15,ALIVE,Chitwan,34500.0,Junior Developer,BIT,4.00,44 year 6 months 18 days,39675.0,34500.0
4,Sita,Female,1991-01-14,ALIVE,Butwal,50000.0,Java Developer,Software Engineer,3.75,35 year 1 months 19 days,50000.0,57500.0
5,Uma,Female,2002-03-19,ALIVE,Pokhara,28000.0,Manager,MBA,3.60,23 year 11 months 14 days,28000.0,32200.0
6,Rajesh,Male,2001-07-21,ALIVE,Damauli,32000.0,Accountant,BBS,3.10,24 year 7 months 12 days,32000.0,32000.0
7,Susma,Female,2004-11-30,ALIVE,Ktm,40000.0,QA Engineer,BSc CSIT,3.85,21 year 3 months 5 days,40000.0,46000.0
8,Susmita,Female,2006-09-12,ALIVE,Lalitpur,22000.0,Intern,+2,2.90,19 year 5 months 21 days,22000.0,22000.0
9,Rita,Female,2000-12-05,ALIVE,Dharan,26000.0,Support Staff,BBA,3.20,25 year 3 months 0 days,26000.0,29900.0
10,Alisha,Female,1969-04-18,ALIVE,Biratnagar,70000.0,Senior Manager,MBA,3.95,56 year 10 months 15 days,70000.0,80500.0
11,Alix,Male,1938-06-22,2010-08-10,Janakpur,90000.0,Director,PhD,4.00,87 year 8 months 11 days,103500.0,90000.0
12,Sudipa,Female,1980-08-17,ALIVE,Hetauda,60000.0,Team Lead,MIT,3.70,45 year 6 months 16 days,60000.0,69000.0
13,Ema,Female,2002-10-09,ALIVE,Ilam,35000.0,Developer,BCA,3.50,23 year 4 months 24 days,35000.0,40250.0
14,Monika,Female,2013-12-31,ALIVE,Nepalgunj,15000.0,Trainee,SEE,2.50,12 year 2 months 5 days,15000.0,15000.0
15,Nisha,Female,2013-02-11,ALIVE,Dang,16000.0,Trainee,SEE,2.60,13 year 0 months 22 days,16000.0,16000.0
16,Abin,Male,2011-03-27,ALIVE,Gorkha,18000.0,Assistant,+2,2.80,14 year 11 months 6 days,18000.0,18000.0
17,Ankit,Male,2003-05-16,ALIVE,Bardiya,42000.0,Engineer,BE,3.40,22 year 9 months 17 days,42000.0,42000.0
18,Tulsi,Female,2000-07-29,ALIVE,Bhairahawa,38000.0,Supervisor,BBA,3.30,25 year 7 months 5 days,38000.0,43700.0
19,Pujan,Male,1999-09-03,ALIVE,Kailali,39000.0,Officer,MBS,3.60,26 year 6 months 2 days,44850.0,39000.0
20,Puja,Female,1997-11-24,ALIVE,Kanchanpur,41000.0,Officer,MBS,3.55,28 year 3 months 9 days,41000.0,47150.0
21,Priti,Female,1996-01-08,ALIVE,Surkhet,43000.0,Analyst,MBA,3.75,30 year 1 months 25 days,43000.0,49450.0
22,Manish,Male,2008-04-14,ALIVE,Palpa,21000.0,Intern,+2,2.70,17 year 10 months 19 days,21000.0,21000.0
23,Laxmi,Female,2007-06-20,ALIVE,Rolpa,23000.0,Clerk,+2,2.85,18 year 8 months 13 days,23000.0,23000.0
24,Bibek,Male,2006-08-25,ALIVE,Jhapa,24000.0,Technician,Diploma,3.00,19 year 6 months 8 days,24000.0,24000.0
25,Milen,Male,2005-10-13,2025-08-11,Lamjung,25000.0,Developer,BIT,3.65,20 year 4 months 20 days,28750.0,25000.0

In [117]:
def up_sal(x):
    if x['Gender'] == 'Male' and x['CGPA'] >= 3:
        return x['Salary'] *1.15
    else:
        return x['Salary']

In [118]:
ep['new_sal'] = ep.apply(up_sal)

KeyError: 'Gender'